name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    services:
      haproxy:
        image: haproxytech/haproxy:alpine-s6-3.4
        volumes:
          - ./test/e2e/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
          - 5555:5555

    steps:
      - name: See if we can reach the HAProxy service
        run: |
          for i in {1..10}; do
            if curl -s -u admin:admin http://localhost:5555; then
              echo "HAProxy is up!"
              exit 0
            fi
            echo "Waiting for HAProxy to start..."
            sleep 2
          done
          echo "HAProxy did not start in time."
          exit 1

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build binary
        run: go build -o bin/traffic-cone ./cmd/traffic-cone

